services:
  crawl4ai:
    image: unclecode/crawl4ai:0.8.0
    container_name: crawl4ai
    restart: unless-stopped
    ports:
      - "11235:11235"
    dns:
      - "1.1.1.1"
      - "8.8.8.8"
    shm_size: "1gb"
